// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var DataJs = require("./data.js");

function userBookmarkData(prim0, prim1) {
  return DataJs.userBookmarkData(prim0, prim1);
}

exports.userBookmarkData = userBookmarkData;
/* ./data.js Not a pure module */
