// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var UserJs = require("./user.js");

function get(prim0, prim1) {
  return UserJs.get(prim0, prim1);
}

exports.get = get;
/* ./user.js Not a pure module */
