// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Server = require("./Server.bs.js");
var Nodeos = require("node:os");
var Nodecluster = require("node:cluster");
var Nodeprocess = require("node:process");

Nodecluster.on("exit", (function (w, c, s) {
        console.log("" + w.process.pid + " exited " + c + " " + s + "");
      }));

var cpuCount = Nodeos.cpus().length;

if (Nodecluster.isPrimary) {
  for(var _i = 1; _i <= cpuCount; ++_i){
    Nodecluster.fork();
  }
  console.log("primary started");
} else {
  Server.start(undefined);
  console.log("Worker " + Nodeprocess.pid + " started");
}

exports.cpuCount = cpuCount;
/*  Not a pure module */
