// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Pg = require("pg");
var Curry = require("rescript/lib/js/curry.js");
var Polka = require("rescript-polka/src/Polka.bs.js");
var Polka$1 = require("polka");
var Dotenv = require("dotenv");
var AppData = require("./app/AppData.bs.js");
var DalUser = require("./dal/DalUser.bs.js");
var Js_dict = require("rescript/lib/js/js_dict.js");

var app = Polka$1();

Dotenv.config();

var app$1 = app.use(function (_req, _res, next) {
      Curry._1(next, undefined);
    });

AppData.userBookmarkData(new Pg.Pool(), "1");

var app$2 = app$1.get("/api/data", (function (_req, res) {
        AppData.userBookmarkData(new Pg.Pool(), "1").then(function (data) {
              Polka.jsonEnd(res, {
                    data: data
                  });
            });
      }));

var app$3 = app$2.get("/user/:id", (function (req, res) {
        var id = Js_dict.get(req.params, "id");
        if (id !== undefined) {
          DalUser.get(new Pg.Pool(), id).then(function (user) {
                if (user !== undefined) {
                  return Polka.jsonEnd(res, {
                              user: user
                            });
                } else {
                  return Polka.jsonEnd(res, {
                              error: "user not found"
                            });
                }
              });
          return ;
        } else {
          return Polka.jsonEnd(res, {
                      error: "missing id"
                    });
        }
      }));

app$3.listen(3000, (function (param) {
        console.log("starting");
      }));

exports.app = app$3;
/* app Not a pure module */
