// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Polka = require("rescript-polka/src/Polka.bs.js");
var Polka$1 = require("polka");

var app = Polka$1();

var app$1 = app.use(function (_req, res, next) {
      Polka.jsonEnd(res, {
            "error!": 400
          });
      Curry._1(next, undefined);
    });

var app$2 = app$1.get("/user", (function (_req, res) {
        res.end("hello!!!");
      }));

app$2.listen(3000, (function (param) {
        console.log("starting");
      }));

exports.app = app$2;
/* app Not a pure module */
