// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var DataJs = require("./data.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

function userFromDb(prim) {
  return DataJs.userFromDb();
}

var email = DataJs.userFromDb().email;

if (email == null) {
  console.log("error: user doesnt want email");
} else {
  console.log("sending email to", email);
}

var user_userName = DataJs.userFromDb().userName;

var user_email = Caml_option.nullable_to_opt(DataJs.userFromDb().email);

var user = {
  userName: user_userName,
  email: user_email
};

var email$1 = user_email;

if (email$1 !== undefined) {
  console.log("sending email to", email$1);
} else {
  console.log("error: user doesnt want email");
}

exports.userFromDb = userFromDb;
exports.user = user;
/* email Not a pure module */
